### PR TITLE
Fixed 'basic binary' test

### PR DESCRIPTION
**Pull request by evert**
When I decode the first test, I get the string `hello`.

### CODE REVIEW

**Comment by mnot** [comment]
See `README.md` - binary test payloads for expected are base32 encoded (so we can test non-UTF8 values).

**Comment by mnot** [comment]
(if that's difficult, we can figure something else out)

**Comment by evert** [comment]
Oh, I missed that.I'm gonna see tomorrow if there's an off-the-shelf package for this. I'd imagine that using plain ASCII or converting it to hexadecimal is likely going to be a bit easier for most implementors (myself included).

**Comment by evert** [comment]
For what it's worth, I found this package which does the job:

https://www.npmjs.com/package/base32-encode

I think I would still recommend doing some kind of hex (or just ascii) format for this, lowering the barrier to entry even more, but feel free to close this if you don't think this is important enough.

**Comment by mnot** [comment]
hex makes sense.

**Pull request closed without merging**
