### PR TITLE
add canonical forms for everything that has one

### LINKED ISSUE #8: Serialisation tests
We need to be able to test the serialisation algorithms too. Probably by annotating when a test is reversible, and/or adding a new member for the canonical form.

### PR DESCRIPTION
**Pull request by phluid61**
closes #8

### CODE REVIEW

**Comment by mnot** [comment]
Looks reasonable; update README?

**Comment by phluid61** [comment]
The hard part :(

**Comment by mnot** [comment]
Q: how is a serialiser supposed to distinguish between string and token?

**Comment by phluid61** [comment]
Oh, yeah. I don't know. I ran my tests in a round trip through the parser, so my serialisation inputs had the appropriate wrapper classes.

**Comment by phluid61** [comment]
I guess the flip-side of the question is: how does a test suite verify that a token wasn't parsed as a string, or _vice versa_?

(Or binary content, for that matter. Not all strings could be base32 data, but all base32 data could be strings.)

**Pull request merged**
