### PR TITLE
update tests to work with draft-11

### PR DESCRIPTION
**Pull request by phluid61**
* new sub-list syntax
* include parameters for all list items
* shrink integers to 15 digits
* parsing "*/*" as a list succeeds now, as a (badly padded) byte sequence

### CODE REVIEW

**Comment by phluid61** [comment]
Uh, I guess this is no longer required, if @mnot jumped right ahead to -12 ?

**Comment by mnot** [comment]
Urgh - I didn't see the PR, sorry; GitHub didn't have me watching the repo, even though I created it :-/

Did I miss anything, as far as you can see?

**Comment by phluid61** [comment]
I've just done a bit of a manual merge.  Only token.json and listlist.json seem to have actual conflicts.

### listlist.json

There's a test for a missing final paren, but not for a missing intermediate one:

* no trailing parenthesis inner list `"(1 2, (3 4)"`

Otherwise mostly there are just a bunch of more specific edge-cases, like:

* empty inner list `"(1),(),(3)"`

or things that are covered in list.json, so not necessary here.

### token.json

The "token with bad start - list" `"*/*"` test -- is that current?  Doesn't it now match a single-element list with a (badly padded) binary?

**Comment by mnot** [comment]
Good catch, thx.

**Pull request merged**
